batch_size: 16
color_space: CIELab
device: cuda:1
input_color_space: RGB
input_size: 512
is_classification: false
loss_function: MSE
out_features: 1
lr: 0.05
map_outputs: true
model_name: ColorCNN_lightness_RGB_normalized
num_epoch: 150
step_size: 20
weight_decay: 0
normalize_rgb: True
normalize_cielab: True
