model_name: "ColorGNN_w_embedding"
data_type: "processed_rgb_w_embedding"
feature_size: 5

loss_function: "CIELab2000"

device: "cuda:2"
lr: 0.02
batch_size: 16
weight_decay: 0
num_epoch: 300

dataset_root: "../destijl_dataset"
