model_name: "ColorGNNSmallEmbedding_toy"
data_type: "processed_rgb_toy_dataset"
feature_size: 1005

threshold_for_neighbours: 1

loss_function: "MSE"

device: "cuda:2"
lr: 0.01
batch_size: 16
weight_decay: 0
num_epoch: 300

node_to_mask: -1