model_name: "ColorCNNBigger"

loss_function: "MSE"
is_classification: False
color_space: "RGB"
map_outputs: True
input_size: 256

device: "cuda:1"
lr: 0.05
batch_size: 16
weight_decay: 0
num_epoch: 150
step_size: 20
