model_name: "ColorGNNEmbedding_cnn"
data_type: "processed_rgb_cnn"
feature_size: 261

threshold_for_neighbours: 0.4

loss_function: "CIELab2000"

device: "cpu"
lr: 0.02
batch_size: 16
weight_decay: 0
num_epoch: 300

dataset_root: "../destijl_dataset"
